server:
  port: 8080 # API Gateway will run on port 8080

spring:
  cloud:
    gateway:
      routes:
        - id: session-management
          uri: https://192.168.1.2:8081
          predicates:
            - Path=/api/sessions/**
        - id: video-chat
          uri: https://192.168.1.2:8083
          predicates:
            - Path=/chat/**,/api/video/**,/topic/**
        - id: termination-service
          uri: https://192.168.1.2:8084
          predicates:
            - Path=/api/termination/**
        - id: matching-service
          uri: https://192.168.1.2:8082
          predicates:
            - Path=/api/matching/**

# Enable Actuator endpoints for easier debugging
management:
  endpoints:
    web:
      exposure:
        include: "*"
